#!/bin/bash -e

#©keithhedger Wed 22 May 19:55:26 BST 2013 kdhedger68713@gmail.com

VERSION=$(sed -n 's/#define VERSION\ "\(.*\)"/\1/p' xdecorations.cpp)

svn commit -m ""
cd /tmp
svn co file:///media/LinuxData/Development/SVN/XDecorations
find XDecorations -name ".svn" -exec rm -r '{}' \; || true
rm /tmp/XDecorations/makepkg
mv /tmp/XDecorations /tmp/XDecorations-${VERSION}

cd /tmp/XDecorations-${VERSION}
make clean
cd ..

tar -czvf XDecorations-${VERSION}.tar.gz XDecorations-${VERSION}
rm -r /tmp/XDecorations-${VERSION}